/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedApplianceRouteImport } from './routes/_authenticated/appliance'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCapacityRouteImport } from './routes/_authenticated/capacity'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedInvestigationsIndexRouteImport } from './routes/_authenticated/investigations.index'
import { Route as AuthenticatedInvestigationsThreadIdRouteImport } from './routes/_authenticated/investigations.$threadId'
import { Route as ApiPublicLiveIngestRouteImport } from './routes/api/public/live-ingest'
import { Route as ApiNettapOllamaChatRouteImport } from './routes/api/nettap/ollama.chat'
import { Route as ApiNettapOllamaShowRouteImport } from './routes/api/nettap/ollama.show'
import { Route as ApiNettapOllamaTagsRouteImport } from './routes/api/nettap/ollama.tags'
import { Route as ApiPublicCollectorHeartbeatRouteImport } from './routes/api/public/collector.heartbeat'
import { Route as ApiPublicCollectorUplinkRouteImport } from './routes/api/public/collector.uplink'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplianceRoute = AuthenticatedApplianceRouteImport.update({
  id: '/appliance',
  path: '/appliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapacityRoute = AuthenticatedCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvestigationsIndexRoute =
  AuthenticatedInvestigationsIndexRouteImport.update({
    id: '/investigations/',
    path: '/investigations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigationsThreadIdRoute =
  AuthenticatedInvestigationsThreadIdRouteImport.update({
    id: '/investigations/$threadId',
    path: '/investigations/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicLiveIngestRoute = ApiPublicLiveIngestRouteImport.update({
  id: '/api/public/live-ingest',
  path: '/api/public/live-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNettapOllamaChatRoute = ApiNettapOllamaChatRouteImport.update({
  id: '/api/nettap/ollama/chat',
  path: '/api/nettap/ollama/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNettapOllamaShowRoute = ApiNettapOllamaShowRouteImport.update({
  id: '/api/nettap/ollama/show',
  path: '/api/nettap/ollama/show',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNettapOllamaTagsRoute = ApiNettapOllamaTagsRouteImport.update({
  id: '/api/nettap/ollama/tags',
  path: '/api/nettap/ollama/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectorHeartbeatRoute =
  ApiPublicCollectorHeartbeatRouteImport.update({
    id: '/api/public/collector/heartbeat',
    path: '/api/public/collector/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCollectorUplinkRoute =
  ApiPublicCollectorUplinkRouteImport.update({
    id: '/api/public/collector/uplink',
    path: '/api/public/collector/uplink',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appliance': typeof AuthenticatedApplianceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/capacity': typeof AuthenticatedCapacityRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/api/chat': typeof ApiChatRoute
  '/investigations/$threadId': typeof AuthenticatedInvestigationsThreadIdRoute
  '/api/public/live-ingest': typeof ApiPublicLiveIngestRoute
  '/investigations/': typeof AuthenticatedInvestigationsIndexRoute
  '/api/nettap/ollama/chat': typeof ApiNettapOllamaChatRoute
  '/api/nettap/ollama/show': typeof ApiNettapOllamaShowRoute
  '/api/nettap/ollama/tags': typeof ApiNettapOllamaTagsRoute
  '/api/public/collector/heartbeat': typeof ApiPublicCollectorHeartbeatRoute
  '/api/public/collector/uplink': typeof ApiPublicCollectorUplinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appliance': typeof AuthenticatedApplianceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/capacity': typeof AuthenticatedCapacityRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/api/chat': typeof ApiChatRoute
  '/investigations/$threadId': typeof AuthenticatedInvestigationsThreadIdRoute
  '/api/public/live-ingest': typeof ApiPublicLiveIngestRoute
  '/investigations': typeof AuthenticatedInvestigationsIndexRoute
  '/api/nettap/ollama/chat': typeof ApiNettapOllamaChatRoute
  '/api/nettap/ollama/show': typeof ApiNettapOllamaShowRoute
  '/api/nettap/ollama/tags': typeof ApiNettapOllamaTagsRoute
  '/api/public/collector/heartbeat': typeof ApiPublicCollectorHeartbeatRoute
  '/api/public/collector/uplink': typeof ApiPublicCollectorUplinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/appliance': typeof AuthenticatedApplianceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/capacity': typeof AuthenticatedCapacityRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/investigations/$threadId': typeof AuthenticatedInvestigationsThreadIdRoute
  '/api/public/live-ingest': typeof ApiPublicLiveIngestRoute
  '/_authenticated/investigations/': typeof AuthenticatedInvestigationsIndexRoute
  '/api/nettap/ollama/chat': typeof ApiNettapOllamaChatRoute
  '/api/nettap/ollama/show': typeof ApiNettapOllamaShowRoute
  '/api/nettap/ollama/tags': typeof ApiNettapOllamaTagsRoute
  '/api/public/collector/heartbeat': typeof ApiPublicCollectorHeartbeatRoute
  '/api/public/collector/uplink': typeof ApiPublicCollectorUplinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/appliance'
    | '/audit'
    | '/capacity'
    | '/cases'
    | '/datasets'
    | '/library'
    | '/live'
    | '/reports'
    | '/sources'
    | '/api/chat'
    | '/investigations/$threadId'
    | '/api/public/live-ingest'
    | '/investigations/'
    | '/api/nettap/ollama/chat'
    | '/api/nettap/ollama/show'
    | '/api/nettap/ollama/tags'
    | '/api/public/collector/heartbeat'
    | '/api/public/collector/uplink'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/appliance'
    | '/audit'
    | '/capacity'
    | '/cases'
    | '/datasets'
    | '/library'
    | '/live'
    | '/reports'
    | '/sources'
    | '/api/chat'
    | '/investigations/$threadId'
    | '/api/public/live-ingest'
    | '/investigations'
    | '/api/nettap/ollama/chat'
    | '/api/nettap/ollama/show'
    | '/api/nettap/ollama/tags'
    | '/api/public/collector/heartbeat'
    | '/api/public/collector/uplink'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/appliance'
    | '/_authenticated/audit'
    | '/_authenticated/capacity'
    | '/_authenticated/cases'
    | '/_authenticated/datasets'
    | '/_authenticated/library'
    | '/_authenticated/live'
    | '/_authenticated/reports'
    | '/_authenticated/sources'
    | '/api/chat'
    | '/_authenticated/investigations/$threadId'
    | '/api/public/live-ingest'
    | '/_authenticated/investigations/'
    | '/api/nettap/ollama/chat'
    | '/api/nettap/ollama/show'
    | '/api/nettap/ollama/tags'
    | '/api/public/collector/heartbeat'
    | '/api/public/collector/uplink'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicLiveIngestRoute: typeof ApiPublicLiveIngestRoute
  ApiNettapOllamaChatRoute: typeof ApiNettapOllamaChatRoute
  ApiNettapOllamaShowRoute: typeof ApiNettapOllamaShowRoute
  ApiNettapOllamaTagsRoute: typeof ApiNettapOllamaTagsRoute
  ApiPublicCollectorHeartbeatRoute: typeof ApiPublicCollectorHeartbeatRoute
  ApiPublicCollectorUplinkRoute: typeof ApiPublicCollectorUplinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appliance': {
      id: '/_authenticated/appliance'
      path: '/appliance'
      fullPath: '/appliance'
      preLoaderRoute: typeof AuthenticatedApplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capacity': {
      id: '/_authenticated/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof AuthenticatedCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/investigations/': {
      id: '/_authenticated/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof AuthenticatedInvestigationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigations/$threadId': {
      id: '/_authenticated/investigations/$threadId'
      path: '/investigations/$threadId'
      fullPath: '/investigations/$threadId'
      preLoaderRoute: typeof AuthenticatedInvestigationsThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/live-ingest': {
      id: '/api/public/live-ingest'
      path: '/api/public/live-ingest'
      fullPath: '/api/public/live-ingest'
      preLoaderRoute: typeof ApiPublicLiveIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nettap/ollama/chat': {
      id: '/api/nettap/ollama/chat'
      path: '/api/nettap/ollama/chat'
      fullPath: '/api/nettap/ollama/chat'
      preLoaderRoute: typeof ApiNettapOllamaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nettap/ollama/show': {
      id: '/api/nettap/ollama/show'
      path: '/api/nettap/ollama/show'
      fullPath: '/api/nettap/ollama/show'
      preLoaderRoute: typeof ApiNettapOllamaShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nettap/ollama/tags': {
      id: '/api/nettap/ollama/tags'
      path: '/api/nettap/ollama/tags'
      fullPath: '/api/nettap/ollama/tags'
      preLoaderRoute: typeof ApiNettapOllamaTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collector/heartbeat': {
      id: '/api/public/collector/heartbeat'
      path: '/api/public/collector/heartbeat'
      fullPath: '/api/public/collector/heartbeat'
      preLoaderRoute: typeof ApiPublicCollectorHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collector/uplink': {
      id: '/api/public/collector/uplink'
      path: '/api/public/collector/uplink'
      fullPath: '/api/public/collector/uplink'
      preLoaderRoute: typeof ApiPublicCollectorUplinkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApplianceRoute: typeof AuthenticatedApplianceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCapacityRoute: typeof AuthenticatedCapacityRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedInvestigationsThreadIdRoute: typeof AuthenticatedInvestigationsThreadIdRoute
  AuthenticatedInvestigationsIndexRoute: typeof AuthenticatedInvestigationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApplianceRoute: AuthenticatedApplianceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCapacityRoute: AuthenticatedCapacityRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedInvestigationsThreadIdRoute:
    AuthenticatedInvestigationsThreadIdRoute,
  AuthenticatedInvestigationsIndexRoute: AuthenticatedInvestigationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicLiveIngestRoute: ApiPublicLiveIngestRoute,
  ApiNettapOllamaChatRoute: ApiNettapOllamaChatRoute,
  ApiNettapOllamaShowRoute: ApiNettapOllamaShowRoute,
  ApiNettapOllamaTagsRoute: ApiNettapOllamaTagsRoute,
  ApiPublicCollectorHeartbeatRoute: ApiPublicCollectorHeartbeatRoute,
  ApiPublicCollectorUplinkRoute: ApiPublicCollectorUplinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
